#!/usr/bin/env sh

set -e

work_dir="${0%/*}"
. "$work_dir"/libs

params=$(cat /dev/stdin)
registry=$(extract_param "$params" .source.registry)
repository=$(extract_param "$params" .source.repository)
username=$(extract_param "$params" .source.username)
password=$(extract_param "$params" .source.password)
previous_number=$(extract_param "$params" .version.number)

ensure_param_set registry
ensure_param_set repository
ensure_param_set username
ensure_param_set password

regctl registry login "$registry" -u "$username" -p "$password"
numbers=$(get_version_numbers "${registry}/${repository}")

if [ -z "$previous_number" ]; then
  >&2 echo "The previous version was not provided. Returning the current version."
  echo "$numbers" | head -1 | numbers_to_versions "${registry}/${repository}"
elif echo "$numbers" | grep -q "$previous_number"; then
  >&2 echo "The previous version was found. Returning the versions since."
  echo "$numbers" | sed -n "/${previous_number}/!p;//q" | numbers_to_versions "${registry}/${repository}"
else
  >&2 echo "The previous version was not found. Returning the current version."
  echo "$numbers" | head -1 | numbers_to_versions "${registry}/${repository}"
fi
