---
platform: linux

inputs:
  - name: source

outputs:
  - name: build

caches:
  - path: source/.gradle

run:
  path: sh
  args:
    - -ecu
    - |
      workdir=$(pwd)

      cd source
      export GRADLE_USER_HOME=$(pwd)/.gradle
      ./gradlew :server:shadowJar

      cd $workdir
      cp -a source/server/build/libs/twocan.server.jar build/app.jar
      cp -a source/server/Dockerfile build/
