---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: twocan
  annotations:
    kapp.k14s.io/delete-strategy: orphan
    kapp.k14s.io/owned-for-deletion: ""
spec:
  dnsNames:
    - e2e.twocan.io
  secretName: twocan-tls
  issuerRef:
    name: issuer-letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
