---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend.yml
  - server.yml
  - ../../secrets/image-pull
patches:
  - path: image-pull-secret.yml
    target:
      kind: Deployment
