---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: twocan/server
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /liveness
              port: 8181
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /readiness
              port: 8181
          envFrom:
            - configMapRef:
                name: server
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    component: server
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
