name: Create Version
description: Creates a new version stored externally that always increments.
inputs:
  bucket:
    description: The bucket where the version is stored.
    required: true
  name:
    description: The name of what is being versioned.
    required: true
  gcp_project:
    description: The GCP project ID of the bucket.
    required: true
  gcp_service_account_key:
    description: The GCP service account used for authentication.
    required: true
outputs:
  version:
    description: The created version.
    value: ${{ steps.version.outputs.version }}
runs:
  using: composite
  steps:
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ inputs.gcp_project }}
        service_account_key: ${{ inputs.gcp_service_account_key }}
        export_default_credentials: true
    - name: Increment version
      id: version
      env:
        bucket: build-versions
        name: twocan
      shell: bash
      run: |
        echo ::group::Setup environment
        set -euo pipefail
        bucket=${{ inputs.bucket }}
        name=${{ inputs.name }}
        version_dir=$(mktemp -d)
        echo ::endgroup::

        echo ::group::Fetch existing version
        if gsutil stat gs://$bucket/$name; then
          gsutil cp gs://$bucket/$name $version_dir
        else
          echo 0 > $version_dir/$name
        fi
        echo ::endgroup::

        version=$(cat $version_dir/$name | xargs expr 1 +)
        echo New version is $version

        echo ::group::Store new version
        echo $version > $version_dir/$name
        gsutil -h Content-Type:text/plain cp $version_dir/$name gs://$bucket
        echo ::endgroup::

        echo ::set-output name=version::$version
