name: Build and Push Container
description: Builds and pushes a container in a standard fashion.
inputs:
  registry:
    description: The registry where the image will be pushed.
    required: true
  username:
    description: The username used to authenticate with the registry.
    required: true
  password:
    description: The password used to authenticate with the registry.
    required: true
  name:
    description: The name of the image in the registry.
    required: true
  version:
    description: The version used to tag the image.
    required: true
  context:
    description: The local path used to build the image.
    required: true
outputs:
  digest:
    description: The digest of the pushed image.
    value: ${{ steps.push.outputs.digest }}
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Registry Login
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and Push Container
      uses: docker/build-push-action@v2
      id: push
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.name }}:v${{ inputs.version }}
