name: End-to-End Test
on:
  push:
  workflow_dispatch:
jobs:
  e2e:
    name: End to End Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome e2e/tests"
